name: Publish Python distribution to TestPyPI

on: 
  push:
    branches:
      - 'feature/2-wheel-action-action'

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build command 1
      run: cmake . -DCMAKE_BUILD_TYPE=Release
    - name: Build command 2
      run: cmake --build . -j

    # Build by cibuildwheel
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5

    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: ./wheelhouse/*.whl
